# Generated by Django 5.2.5 on 2025-08-11 22:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(help_text='Nombre original del archivo PDF', max_length=255)),
                ('tamaño_bytes', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes')),
                ('texto_extraido', models.TextField(db_index=True, help_text='Texto completo extraído del PDF', validators=[django.core.validators.MinLengthValidator(1)])),
                ('metodo_extraccion', models.CharField(choices=[('pypdf', 'PyPDF2 - Texto directo'), ('ocr', 'OCR - Reconocimiento óptico')], help_text='Método utilizado para extraer el texto', max_length=50)),
                ('tiempo_procesamiento', models.DecimalField(blank=True, decimal_places=3, help_text='Tiempo de procesamiento en segundos', max_digits=8, null=True)),
                ('fecha_procesamiento', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora de procesamiento')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('eliminado', models.BooleanField(db_index=True, default=False, help_text='Indica si el documento fue eliminado lógicamente')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha de eliminación lógica', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que subió el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Procesado',
                'verbose_name_plural': 'Documentos Procesados',
                'ordering': ['-fecha_procesamiento'],
                'indexes': [models.Index(fields=['usuario', 'eliminado'], name='doc_usuario_eliminado_idx'), models.Index(fields=['usuario', 'fecha_procesamiento'], name='doc_usuario_fecha_idx'), models.Index(fields=['eliminado', 'fecha_procesamiento'], name='doc_global_fecha_idx')],
            },
        ),
    ]
